### ISSUE TITLE
Possible forwarding issue.

### ISSUE THREAD

**Issue by Macmod** [brunonova/drmips#5] opened 2017-04-26 14:37 UTC
Take this snippet of code with the pipeline-extended CPU:

li $t0, 100
li $t4, 12
sw $t0, 0($t4) <— Writing-back (A)
nop
addi $t4, $t4, 4
addi $t0, $t0, 1 <— Decoding (B)

It should leave 101 in $t0, but it actually forwards $t4's value from the write-back stage of (A) into $t0 during the decode stage of (B), resulting in $t0 = 13. This does not happen with forwarding from other stages if I remove some of the middle instructions. I feel this is a forwarding bug, but let me know if it's somehow intended behaviour...

**Comment by Macmod** [comment] 2017-04-26 15:36
(The add $t4, $t4, 1 line is useless, could be replaced with a nop for demonstration purposes)

**Comment by brunonova** [comment] 2017-04-26 19:23
You're right! When I use the unicycle CPU I get a different result, so there's a bug.

I think the problem is in the Register Bank.
When the last instruction is in the Decoding stage (B), the Register Bank is incorrectly forwarding `WriteData` into the outputs because it's not checking the `RegWrite` control signal.

I don't have a lot of free time now, so it will take some time for me to release a new version.

**Comment by Macmod** [comment] 2017-04-26 23:59
I managed to put together a quick fix with your comment in mind. Hope this is resolved soon. 
Thanks for the quick response, @brunonova. :+1:

**Comment by brunonova** [comment] 2017-04-28 19:45
Your commit fixed the bug, so I'm closing this bug.

I'll release a new version shortly.
Thanks again!

**Closed by brunonova** 2017-04-28 19:45 UTC
Labels: bug

**Comment by brunonova** [comment] 2017-04-28 21:09
New version released!
